
# GaussPivot configuration
matrix:
  - [2, 1, 1, 0, 0, 0]
  - [4, 3, 3, 1, 0, 0]
  - [8, 7, 9, 5, 1, 0]
  - [6, 7, 9, 8, 6, 1]
  - [2, 3, 4, 5, 6, 7]
  - [4, 5, 6, 7, 8, 9]
vector:
  - [1]
  - [2]
  - [3]
  - [4]
  - [5]
  - [6]
pause: 1
